//export all action variables here


//USER ACTIONS
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

//GROUPS
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS";
export const UPDATE_GROUP_SUCCESS = "UPDATE_GROUP_SUCCESS";


//CHANNELS
export const GET_CHANNELS = "GET_CHANNELS";
export const CREATE_CHANNEL_GROUP_SUCCESS = "CREATE_CHANNEL_GROUP_SUCCESS";
export const CREATE_CHANNEL_PRIVATE_SUCCESS = "CREATE_CHANNEL_PRIVATE_SUCCESS";
export const DELETE_CHANNEL_SUCCESS = "DELETE_CHANNEL_SUCCESS";
export const UPDATE_CHANNEL_SUCCESS = "UPDATE_CHANNEL_SUCCESS";


export const SEND_MESSAGE = 'SEND_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
